#!/bin/bash
./clear
find . * -maxdepth 0 -type d ! -path . ! -name obsolete -execdir zip -r '{}.zip' '{}' \;
tar cf samples.tar *.zip
rm -f *.zip
scp samples.tar greenlaw110.com:act/skeleton
rm -f samples.tar
